name: Coverity with Self-Hosted Runner

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted]

    env:
      COVERITY_URL: ${{ secrets.COVERITY_URL }}
      COV_USER: ${{ secrets.COVERITY_USER }}
      COVERITY_PASSPHRASE: ${{ secrets.COVERITY_PASSPHRASE }}
      COVERITY_LICENSE: ${{ secrets.COVERITY_LICENSE }}
      SECURITY_GATE_VIEW: OWASP Web Top 10
      COVERITY_CHECKERS: --webapp-security
      SYNOPSYS_GITHUB_TOOLS_REPO: https://github.com/synopsys-sig-community/synopsys-github-tools

    steps:
      - uses: actions/checkout@v2

      - name: Get Synopsys GitHub Tools
        run: |
          git clone -q --depth 1 $SYNOPSYS_GITHUB_TOOLS_REPO
          pip3 install --upgrade pandas requests==2.26.0 urllib3==1.26.7 jsonapi-requests==0.6.2 tenacity==6.2.0 pygithub

      - name: Coverity License
        run: |
          echo $COVERITY_LICENSE > coverity-license.dat

      - name: Create Coverity Stream
        if: ${{github.event_name == 'push'}}
        # TODO: Should this only run for master, other specific names?
        run: |
          env
          export COVERITY_STREAM_NAME=${GITHUB_REPOSITORY##*/}-${GITHUB_REF##*/}
          echo Ensure that stream "$COVERITY_STREAM_NAME" exists
          cov-manage-im --url $COVERITY_URL --on-new-cert trust --mode projects --add --set name:"$COVERITY_STREAM_NAME" || true
          cov-manage-im --url $COVERITY_URL --on-new-cert trust --mode streams --add -set name:"$COVERITY_STREAM_NAME" || true
          cov-manage-im --url $COVERITY_URL --on-new-cert trust --mode projects --update --name "$COVERITY_STREAM_NAME" --insert stream:"$COVERITY_STREAM_NAME"

      - name: Coverity Scan (Full analysis)
        if: ${{github.event_name == 'push'}}
        run: |
          export COVERITY_STREAM_NAME=${GITHUB_REPOSITORY##*/}-${GITHUB_REF##*/}
          # XXX For ProFtpd C/C++ project
          ./configure
          cov-build --dir idir make all
          # XXX For ProFtpd C/C++ project
          # Alternatively use cov-capture
          # cov-capture --project-dir . --idir idir
          cov-analyze --dir idir --strip-path `pwd` --security-file coverity-license.dat $COVERITY_CHECKERS
          cov-commit-defects --dir idir --security-file coverity-license.dat --ticker-mode none --url $COVERITY_URL --on-new-cert trust --stream $COVERITY_STREAM_NAME --scm git --description "GitHub Workflow $GITHUB_WORKFLOW for $GITHUB_REPO" --version $GITHUB_SHA
          cov-format-errors --dir idir --security-file coverity-license.dat --json-output-v8 coverity-full-results.json

      - name: Export Coverity Results to SARIF (Full)
        run: |
          python3 ./synopsys-github-tools/github-export-coverity-issues.py --coverity-json coverity-full-results.json --debug 9
        if: ${{github.event_name == 'push'}}

      - name: Get Pull Request Changeset
        if: ${{ github.event_name == 'pull_request' }}
        id: changeset
        uses: jitterbit/get-changed-files@v1
        with:
          format: json

      - name: Coverity Scan (Incremental analysis)
        if: ${{github.event_name == 'pull_request'}}
        run: |
          env
          export COVERITY_STREAM_NAME=${GITHUB_REPOSITORY##*/}-$BASE_BRANCH
          echo ${{ steps.changeset.outputs.added_modified }}
          readarray -t changed_files <<<"$(jq -r '.[]' <<<'${{ steps.changeset.outputs.added_modified }}')"
          for changed_file in ${changed_files[@]}; do
            echo ${changed_file} >> coverity-files-to-scan.txt
            echo "Scan changed file ${changed_file}."
          done
          # XXX For ProFtpd C/C++ project
          ./configure
          cov-run-desktop --dir idir --strip-path `pwd` --url $COVERITY_URL --stream                    $COVERITY_STREAM_NAME --build make all
          # XXX For ProFtpd C/C++ project
          # Alternatively use cov-capture
          # cov-capture --dir idir --source-list coverity-files-to-scan.txt
          cov-run-desktop --dir idir --strip-path `pwd` --url $COVERITY_URL --stream $COVERITY_STREAM_NAME --present-in-reference false \
            --ignore-uncapturable-inputs true --exit1-if-defects true coverity-files-to-scan.txt \
            --json-output-v7 coverity-incremental-results.json
        env:
          BASE_BRANCH: ${{ github.base_ref }}

      #- name: Comment on pull request (Incremental)
      #  run: python3 ./synopsys-github-tools/synopsys-github-tools/github-coverity-comment-on-pull-request.py --coverity-json coverity-incremental-results.json --url $COVERITY_URL --stream $COVERITY_STREAM_NAME --debug 9
      #  if: ${{github.event_name == 'pull_request'}}
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  continue-on-error: true

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: synopsys-coverity-github-sarif.json

      - name: Coverity Security Gate
        if: ${{github.event_name == 'push'}}
        run: |
          COVERITY_STREAM_NAME=${GITHUB_REPOSITORY##*/}-${GITHUB_REF##*/}
          COVERITY_VIEW_ESCAPED=`jq -rn --arg x "$SECURITY_GATE_VIEW" '$x|@uri'`
          curl -kfLsS --user $COV_USER:$COVERITY_PASSPHRASE $COVERITY_URL/api/viewContents/issues/v1/$COVERITY_VIEW_ESCAPED?projectId=$COVERITY_STREAM_NAME > security-gate-results.json
          if [ $(cat security-gate-results.json | jq .viewContentsV1.totalRows) -ne 0 ]; then cat security-gate-results.json | jq .viewContentsV1.rows; exit 1; fi

